### ISSUE TITLE
【疑似bug】【2条】Application的继承关系异常、额外的混淆配置

### ISSUE THREAD

**Issue by qaszxcwer** [JustGank/AppJoint2#1]
### Application继承关系异常
项目下有2个module存在Application，分别是app/TestApplication和AppBaseFrame/BaseApplication
其中TestApplication继承了BaseApplication，BaseApplication中在onCreate中初始化了整个App的context，用于网络请求和toast之类的操作
引入AppJoint2之后，给TestApplication加了注解@AppSpec
在没有混淆的情况下，按照预期正常工作
开启混淆之后，在发起网络请求时报错，BaseApplication里面的context是lateInit的，却在使用前没有被初始化
给BaseApplication加上@ModuleSpec注解后恢复正常
**请问这是什么原因导致的？他们存在继承关系，为什么子类加了注解之后会不能正常执行父类的生命周期？**

### 项目使用简介建议添加混淆注意点
我在接入使用的过程中，发现混淆后无法正常跨模块使用，试着给涉及到跨模块的接口和实现类加上了-keep才正常
不清楚这是bug还是特性？因为在公司接触到的AppJoint是没有另外设置混淆的，望解答
如为特性，希望能够在使用简介中加入混淆提示，也算是帮后来人踩坑了

以上接入的代码已经加入了我自己的[框架库](https://github.com/qaszxcwer/AndroidApp_MVVM_Framework)中，如有疑问可以拉取代码

**Comment by JustGank** [comment]
1.解决这类问题可以通过反编译Apk的方式定位。
使用你的项目打了一个release包，去掉了BaseApplication的@Module注解。
反编译后发现问题为:
`public final class TestApplication extends Application`
即编译后TestApplication 的父类 由 BaseApplication 被替换为 Applicaiton，所以你再使用BaseApplication中的变量会报空。
这也能解释为什么你加了@ModuleSpec 注解之后会可用，因为此时的BaseApplication虽然不再以父类的身份被初始化，但是他会以子Application的方式被初始化，此时使用的上下文是TestApplication的。

2.为什么 `TestApplication extends Application`
应该是混淆之后真正的TestApplication 已经改变了名称，但是ASM插装记录的是原始路径，基于这个路径又生出来一个TestApplication，但是这个TestApplication 并不是开发者自身的。

3.如何解决：
-keep class com.example.mvvmframe.zTest.LoginAjImpl {*;}
-keep class com.appjoint2.core.AppJoint2 {*;}
-keep class com.example.mvvmframe.TestApplication {*;}

**Comment by qaszxcwer** [comment]
> 1.解决这类问题可以通过反编译Apk的方式定位。 使用你的项目打了一个release包，去掉了BaseApplication的@module注解。 反编译后发现问题为: `public final class TestApplication extends Application` 即编译后TestApplication 的父类 由 BaseApplication 被替换为 Applicaiton，所以你再使用BaseApplication中的变量会报空。 这也能解释为什么你加了@ModuleSpec 注解之后会可用，因为此时的BaseApplication虽然不再以父类的身份被初始化，但是他会以子Application的方式被初始化，此时使用的上下文是TestApplication的。
> 
> 2.为什么 `TestApplication extends Application` 应该是混淆之后真正的TestApplication 已经改变了名称，但是ASM插装记录的是原始路径，基于这个路径又生出来一个TestApplication，但是这个TestApplication 并不是开发者自身的。
> 
> 3.如何解决： -keep class com.example.mvvmframe.zTest.LoginAjImpl {_;} -keep class com.appjoint2.core.AppJoint2 {_;} -keep class com.example.mvvmframe.TestApplication {*;}

对于第一个问题，我也回头看了一遍appjoint作者的文章，这个appspec注解是用来在需要项目中既要单独运行模块、又要能够全量编译的场景下，和modulespec配合使用的，我的框架项目暂时还没有这样的场景，所以不需要添加appspec注解。
当然为了以后不要重复踩坑，最好现在就加上注解，然后按照你给出的解决方案处理好继承问题，非常感谢你的解答，通过反编译的方法查找问题原因是我之前没有接触过的，又涨知识了。

经过实践，解决**第一个问题**的最小化规则是仅keep我自己的TestApplication，对com.appjoint2.core.AppJoint2和com.example.mvvmframe.zTest.LoginAjImpl的keep规则是多余的（仅考虑第一个问题，不考虑使跨模块调用正常工作）

至于**第二个问题**，需要额外添加混淆规则的情况（本例中即为keep ILoginAj和LoginAjImpl），还是麻烦作出明确的解答，是bug还是为了适配AGP8.0的特性？我在公司项目中已经确认了原版的appjoint是不需要keep接口和实现类的

**Comment by qaszxcwer** [comment]
非常抱歉，**第二个问题**是个我自己的低级错误，我今天因为其他需求详细检查了一遍build.gradle文件，才发现公司的代码几年前就把混淆给关闭了，所以才会出现不需要给appjoint的接口和实现类添加keep规则也能正常工作的情况
